version: "3"

vars:
  PROJECT_NAME: mics-r4
  BUILD_DIR: build
  BIN_DIR: bin
  BUILD_TYPE: Debug

tasks:
  default:
    desc: メインタスクを表示
    cmds:
      - task -l

  # Debugビルド
  build:debug:
    desc: デバッグビルド (-Wall -g)
    deps:
      - build:prepare
    cmds:
      - cd {{.BUILD_DIR}} && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
      - echo "✓ Debugビルド完了"

  # Releaseビルド
  build:release:
    desc: リリースビルド (-Wall -O2)
    deps:
      - build:prepare
    cmds:
      - cd {{.BUILD_DIR}} && cmake -DCMAKE_BUILD_TYPE=Release .. && make
      - echo "✓ Releaseビルド完了"

  # デフォルトのビルド（Debug）
  build:main:
    desc: メインプロジェクトをビルド（Debugモード）
    cmds:
      - task: build:debug

  build:prepare:
    desc: ビルドディレクトリを作成
    cmds:
      - mkdir -p {{.BUILD_DIR}}

  build:clean:
    desc: ビルドファイルをクリーン
    cmds:
      - rm -rf {{.BUILD_DIR}}/*

  build:rebuild:
    desc: クリーンしてからビルドし直す
    deps:
      - build:clean
      - build:main

  run:chainhash:
    desc: chainhashを実行
    deps:
      - build:main
    cmds:
      - ./{{.BUILD_DIR}}/chainhash {{.CLI_ARGS}}

  # mnistview Debugビルド
  tools:mnistview:build:debug:
    desc: mnistviewをデバッグビルド
    dir: tools/mnistview
    cmds:
      - mkdir -p build
      - cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
      - cp build/mnistview ../../{{.BIN_DIR}}/
      - echo "✓ mnistview Debugビルド完了"

  # mnistview Releaseビルド
  tools:mnistview:build:release:
    desc: mnistviewをリリースビルド
    dir: tools/mnistview
    cmds:
      - mkdir -p build
      - cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
      - cp build/mnistview ../../{{.BIN_DIR}}/
      - echo "✓ mnistview Releaseビルド完了"

  # デフォルトのmnistviewビルド（Debug）
  tools:mnistview:build:
    desc: mnistviewをビルド（Debugモード）
    cmds:
      - task: tools:mnistview:build:debug

  tools:mnistview:run:
    desc: mnistviewを実行
    deps:
      - tools:mnistview:build
    cmds:
      - ./{{.BIN_DIR}}/mnistview {{.CLI_ARGS}}

  test:run:
    desc: テストを実行
    deps:
      - build:main
    cmds:
      - cd {{.BUILD_DIR}} && ctest --output-on-failure

  clean:
    desc: すべての生成物を削除
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.BIN_DIR}}
      - rm -rf tools/mnistview/build

  cmake:configure:
    desc: CMakeを設定
    deps:
      - build:prepare
    cmds:
      - cd {{.BUILD_DIR}} && cmake ..

  dev:setup:
    desc: 開発環境をセットアップ
    deps:
      - build:prepare
      - cmake:configure

  # フォーマット関連
  format:
    desc: すべてのC++ファイルをフォーマット
    cmds:
      - find . -name "*.cc" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format -i
      - echo "✓ フォーマット完了"

  format:check:
    desc: フォーマットのチェック（変更があればエラー）
    cmds:
      - find . -name "*.cc" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format --dry-run --Werror


