version: "3"

vars:
  PROJECT_NAME: mics-r4
  BUILD_DIR: build
  BIN_DIR: bin
  BUILD_TYPE: Debug

tasks:
  default:
    desc: メインタスクを表示
    cmds:
      - task --list-all --sort none

  setup:
    desc: 開発環境をセットアップ
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - mkdir -p {{.BIN_DIR}}

  build:
    desc: デバッグビルド (-Wall -g)
    deps:
      - setup
    cmds:
      - cd {{.BUILD_DIR}} && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
      - cp {{.BUILD_DIR}}/main {{.BIN_DIR}}/

  build:release:
    desc: リリースビルド (-Wall -O2)
    deps:
      - setup
    cmds:
      - cd {{.BUILD_DIR}} && cmake -DCMAKE_BUILD_TYPE=Release .. && make
      - cp {{.BUILD_DIR}}/main {{.BIN_DIR}}/

  build:mnistview:
    desc: mnistviewをデバッグビルド
    deps:
      - setup
    dir: tools/mnistview
    cmds:
      - mkdir -p build
      - cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make
      - cp build/mnistview ../../{{.BIN_DIR}}/

  build:mnistview:release:
    desc: mnistviewをリリースビルド
    deps:
      - setup
    dir: tools/mnistview
    cmds:
      - mkdir -p build
      - cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
      - cp build/mnistview ../../{{.BIN_DIR}}/

  build:clean:
    desc: ビルドファイルをクリーン
    cmds:
      - rm -rf {{.BUILD_DIR}}/*

  run:
    desc: メインプログラムを実行
    cmds:
      - ./{{.BIN_DIR}}/main {{.CLI_ARGS}}

  run:mnistview:
    desc: mnistviewを実行
    cmds:
      - ./{{.BIN_DIR}}/mnistview {{.CLI_ARGS}}

  test:
    desc: テストを実行
    deps:
      - build
    cmds:
      - sh -c 'if [ -n "{{.CLI_ARGS}}" ]; then cd {{.BUILD_DIR}} && ctest -R "{{.CLI_ARGS}}" --output-on-failure; else cd {{.BUILD_DIR}} && ctest --output-on-failure; fi'

  format:
    desc: すべてのC++ファイルをフォーマット
    cmds:
      - find . -name "*.cc" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format -i

  format:check:
    desc: フォーマットのチェック
    cmds:
      - find . -name "*.cc" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format --dry-run --Werror
